
/run/initialize



# energy 1

/gps/source/multiplevertex true

/gps/source/intensity 10.
/gps/particle neutron
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/radius 2.5 mm
/gps/pos/halfz .5 mm
/gps/ang/type iso
/gps/ang/rot1 1 0 0
#/gps/ang/rot2 0 0 1
/gps/ene/mono 511 keV 
/gps/ang/maxtheta 1 deg
/gps/pos/centre 0 0 6.35 cm

# energy 2
/gps/source/add 10.
/gps/particle neutron
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/radius 2.5 mm
/gps/pos/halfz .5 mm
/gps/ang/type iso
/gps/ang/rot1 1 0 0
#/gps/ang/rot2 0 0 1
/gps/ene/mono 1274.537 keV 
/gps/ang/maxtheta 1 deg
/gps/pos/centre 0 0 6.35 cm



# run both
