#This sets the gps up to shoot an optical photon

/run/initialize

#/gps/source/add 5

/gps/particle neutron
/gps/pos/type Point
/gps/pos/centre 300 0 0
/gps/ang/type iso
/gps/ang/mintheta 89.27 deg
/gps/ang/maxtheta 90.73 deg
/gps/ang/minphi 0.242 deg
/gps/ang/maxphi -0.242 deg
/gps/ene/type Mono
/gps/ene/mono 1 MeV


#/gun/particle gamma
#/gun/energy 661.7 keV
#/gun/position 0 5 -20.32
#/gun/direction 0 -1 0
#/gun/polarization 0 1 0

/tracking/verbose 0

/run/beamOn 100000
